in:
  type: file
  path_prefix: /Users/hsato/OpenProjects/embulk/embulk-support/twitter_add_time_column/./csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
filters:
- type: column
  add_columns:
    - src: time
      name: add_time
#      type: string
#      format: "%Y/%m/%d"
- type: typecast
  columns:
    - name: add_time
      type: string
      format: "%Y/%m/%d"
- type: calcite
  query: 'select "add_time","comment","purchase","time","account","id"  from $PAGES'
out: {type: stdout}
