in:
  type: file
  path_prefix: /private/tmp/hoge/csv/sample_
#  decoders:
#  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: string, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: string, format: '%Y%m%d'}
    - {name: comment, type: string}
#out: {type: stdout}
filters:
- type: timestamp_format
  default_from_timestamp_format: ["%Y-%m-%d %H:%M:%S", "%Y%m%d"]
  columns:
  - {name: time, type: timestamp }
  - {name: purchase, type: timestamp }
out:
  type: mysql
  user: user
  password: password
  mode: merge
  table: example
  database: embulk_test
  host: localhost
  column_options:
    id: { type: 'int primary key' }

