in:
  type: file
  path_prefix: sample.csv
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: first_name, type: string}
    - {name: age, type: double}
    - {name: gender, type: string}
filters:
  - type: typecast
    columns:
    - {name: id, type: long}
    - {name: first_name, type: string}
    - {name: age, type: long}
    - {name: gender, type: string}
    
out: {type: stdout}
